### PR TITLE
Create greengrocer.json

### PR DESCRIPTION
**Pull request by greengorcer**

### CODE REVIEW

**Comment by greengorcer** [comment]
m31

**Comment by szabgab** [comment]
Why did you close this PR? Don't you want me to integrate it?

**Comment by greengorcer** [comment]
It was totally a mistake. Now  I learn what close the pull request means...

I just find my usual avatar photo file. Just updated it here.

Thanks a lot.

IMG_0003

**Comment by szabgab** [comment]
ok, just to clarify adding an image to the PR does not update your avatar. Not even if it as cool as being on an aircraft carrier :)

**Comment by szabgab** [comment]
Oh and I see there was a typo in the filename

**Comment by szabgab** [comment]
Would you like to fix it, or shall I fix it? `greengrocer` => `greengorcer`  both in the filename and in the value of github in the file.

**Comment by szabgab** [comment]
I fixed it.

**Pull request merged**
